apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-deployment
  labels:
    app: address
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address
  template:
    metadata:
      labels:
        app: address
    spec:
      containers:
      - name: address
        image: theresetaylor/address-service:v2
        ports:
        - containerPort: 5000  

---
apiVersion: v1
kind: Service
metadata:
  name: address-service
spec:
  type: ClusterIP
  selector:
    app: address
  ports:
    - port: 80           
      targetPort: 5000   
