apiVersion: apps/v1
kind: Deployment
metadata:
  name: degree-deployment
  labels:
    app: degree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: degree
  template:
    metadata:
      labels:
        app: degree
    spec:
      containers:
      - name: degree
        image: theresetaylor/degree-service:v3
        ports:
        - containerPort: 5002  

---
apiVersion: v1
kind: Service
metadata:
  name: degree-service
spec:
  type: ClusterIP
  selector:
    app: degree
  ports:
    - port: 80           
      targetPort: 5002    
