apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-api-deployment
  labels:
    app: upload-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-api
  template:
    metadata:
      labels:
        app: upload-api
    spec:
      containers:
      - name: upload-api
        image: similabs/upload-api:v1
        ports:
        - containerPort: 5000
